language: python
python:
  - "3.6"
stages:
  - before_install
  - install
  - script
  - before_deploy
  - name: after_success
    if: branch = master
  - deploy

before_install:
#  - sudo apt-get update
#  - sudo apt-get install python-dev
  - . version.sh
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

install:
  - ls -alh
#  - python setup.py install
  - docker build -t $DOCKER_ACCT/$DOCKER_REPO .
  - docker tag $DOCKER_ACCT/$DOCKER_REPO $DOCKER_ACCT/$DOCKER_REPO:build-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_ACCT/$DOCKER_REPO:build-$TRAVIS_BUILD_NUMBER

script:
#  - cd tests
#  - python -m unittest discover --verbose --start-directory .
#  - cd ..
  - echo "done script"

before_deploy:
#  - python setup.py sdist
  - echo "before deploy"

after_success:
  - docker tag $DOCKER_ACCT/$DOCKER_REPO $DOCKER_ACCT/$DOCKER_REPO:latest
  - docker push $DOCKER_ACCT/$DOCKER_REPO:latest
  - echo "Done"

deploy:
  provider: pypi
  user: $DEPLOY_PYPI_USER
  password: $DEPLOY_PYPI_PASS
  skip_existing: true
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH == release-*