# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    hostname: mongo
    ports:
      - 42522:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ADMIN
      MONGO_INITDB_ROOT_PASSWORD: $ROOT_PASSWORD

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 42521:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ADMIN
      ME_CONFIG_MONGODB_ADMINPASSWORD: $ROOT_PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_WEB
      ME_CONFIG_BASICAUTH_PASSWORD: $ROOT_PASSWORD

